#!/usr/bin/env python
import argparse, sys

parser = argparse.ArgumentParser()
parser.add_argument('filename', nargs='?')
args = parser.parse_args()

if args.filename:
    string = open(args.filename).read()
elif not sys.stdin.isatty():
    string = sys.stdin.read()
else:
    parser.print_help()
    exit(0)


from tables import *

dat = read(string)[0]

#i, v0, v = dat

#delta = 100 * abs((v0 - v)/v0)

#new_table = table([dat, delta])

f = open('OUT_FILE.dat', 'w')
write(new_table, f)
